import { useState, useEffect, useRef } from 'react';
import socket from '../socket/socket';
import { useNavigate } from 'react-router-dom';

export const useWebRTC = (roomId) => {
  const navigate = useNavigate();
  //..
  //..for videos things keep revising this and also more focus..
  const [localStream, setLocalStream] = useState(null);
  const [remoteStream, setRemoteStream] = useState(null);
  const [isVideoEnabled, setIsVideoEnabled] = useState(true);
  const [isAudioEnabled, setIsAudioEnabled] = useState(true);
  const [incomingCall, setIncomingCall] = useState(null);

  //
  //.. 
  //ref for HTML video elements
  const localVideoRef = useRef(null);
  const remoteVideoRef = useRef(null);
  //..
  //..
  // We use useRef for the RTCPeerConnection instead of useState.
  // 1. Mutable Object: RTCPeerConnection is a complex object that manages its own internal state (network, ICE candidates, etc.).
  // 2. No Re-renders: We don't want React to re-render the entire UI every time the connection state changes internally.
  // 3.(main point) Persistence: useRef keeps the exact same connection object alive across component re-renders.
  const peerConnectionRef = useRef(null);

  //..
  //..initialice it..
  const rtcConfigiceServers = {
    iceServers: [
      {
        urls: "stun:stun.l.google.com:19302", // Google's public STUN server (free)
      },
    ],
  };
  //..
  //....

  //..
  //..
  //LOCAL camera and mic access;
  useEffect(() => {
    const getMedia = async () => {
      try {
        const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true });
        setLocalStream(stream);
        if (localVideoRef.current) {
          localVideoRef.current.srcObject = stream;
        }
      } catch (err) {
        console.log(err);
      }
    };
    getMedia();
  }, []);

  const toggleVideo = () => {
    if (localStream) {
      const videoTrack = localStream.getVideoTracks()[0];
      if (videoTrack) {
        videoTrack.enabled = !videoTrack.enabled;
        setIsVideoEnabled(videoTrack.enabled);
      }
    }
  };

  const toggleAudio = () => {
    if (localStream) {
      const audioTrack = localStream.getAudioTracks()[0];
      if (audioTrack) {
        audioTrack.enabled = !audioTrack.enabled;
        setIsAudioEnabled(audioTrack.enabled);
      }
    }
  };

  //..
  //...
  ///....
  //for second person when i need to connect someone..
  const createPeerConnection = () => {
    const pc = new RTCPeerConnection(rtcConfigiceServers);

    if (localStream) {
      localStream.getTracks().forEach((track) => {
        pc.addTrack(track, localStream);
      });
    }

    pc.ontrack = (event) => {
      console.log("Got remote track!", event.streams[0]);
      setRemoteStream(event.streams[0]);
      if (remoteVideoRef.current) {
        remoteVideoRef.current.srcObject = event.streams[0];
      }
    };

    // 3. Listen for ICE candidates generated by our browser
    pc.onicecandidate = (event) => {
      if (event.candidate) {
        // Send this candidate to the other peer via Socket.io
        socket.emit("webrtc-ice-candidate", {
          roomId, // Assuming you have the roomId from your URL search params
          candidate: event.candidate,
        });
      }
    };

    peerConnectionRef.current = pc;
    return pc;
  };

  //..
  //....
  // Handling the signal via socket.io
  useEffect(() => {
    
    //..
    // 1. "user-joined": Koi naya banda room me aaya.
    // Pehle offer bhejte the ab sirf incoming call alert set karenge
    socket.on("user-joined", (userID) => {
      console.log("remote user joined: ",userID);
      setIncomingCall(userID);
    });
    //...

    //..
    // 2. "webrtc-offer": Kisi aur ne mujhe Offer (call request) bheja hai.
    socket.on("webrtc-offer", async ({ offer }) => {
      console.log("Received an offer, creating answer");
      // Main apna connection object ready kar raha hu (taki main unki call utha saku)
      const pc = createPeerConnection();
      
      // Unka bheja hua offer main apna "Remote Description" set kar raha hu (Unki details browser ko de raha hu)
      await pc.setRemoteDescription(new RTCSessionDescription(offer));
      
      // Ab main apna "Answer" banaunga
      const answer = await pc.createAnswer();
      
      // Apne answer ko main apna "Local Description" set kar raha hu
      await pc.setLocalDescription(answer);
      
      // Answer wapas socket ke through us user ko bhej raha hu
      socket.emit("webrtc-answer", { roomId, answer });
    });
    //...

    //..
    // 3. "webrtc-answer": Kisi ne mere Offer ka Answer de diya hai (Call utha li).
    socket.on("webrtc-answer", async ({ answer }) => {
      console.log("answer recived: ",answer);
      // Agar mera connection abhi zinda hai, toh unka answer "Remote Description" me set kar dunga
      if (peerConnectionRef.current) {
        // Yaha mene ek typo fix kar diya tha (newRTCSessionDescription ko new RTCSessionDescription kiya tha)
        await peerConnectionRef.current.setRemoteDescription(new RTCSessionDescription(answer));
      }
    });
    //...

    //..
    // 4. "webrtc-ice-candidate": P2P connection ke liye raaste (paths/IP/ports) mil gaye!
    socket.on("webrtc-ice-candidate", async ({ candidate }) => {
      // Jab bhi samne wale browser ko naya rasta milta hai wo mujhe ICE candidate bhejta hai.
      // Main usko apne connection me add kar leta hu taki connection ban jaye.
      if (peerConnectionRef.current) {
        await peerConnectionRef.current.addIceCandidate(new RTCIceCandidate(candidate));
      }
    });
    //...

    //..
    //....
    socket.on("call-rejected", () => {
      alert("Call was rejected");
      navigate("/");
    });

    return () => {
      // Cleanup function: Jab main component se bahar niklu (room leave karu),
      // Toh saare event listeners hata dunga warna multiple times event chalne lag jayega (memory leak).
      socket.off("user-joined");
      socket.off("webrtc-offer");
      socket.off("webrtc-answer");
      socket.off("webrtc-ice-candidate");
      socket.off("call-rejected");
    };
  }, [roomId, localStream, navigate]);
  //..

  const acceptCall = async () => {
    if (!incomingCall) return;
    const pc = createPeerConnection();
    const offer = await pc.createOffer();
    await pc.setLocalDescription(offer);
    socket.emit("webrtc-offer", {
      targetSocketId: incomingCall,
      offer,
      roomId,
    });
    setIncomingCall(null);
  };

  const rejectCall = () => {
    if (!incomingCall) return;
    socket.emit("reject-call", { targetSocketId: incomingCall });
    setIncomingCall(null);
  };

  return {
    localStream,
    remoteStream,
    isVideoEnabled,
    isAudioEnabled,
    incomingCall,
    localVideoRef,
    remoteVideoRef,
    toggleVideo,
    toggleAudio,
    acceptCall,
    rejectCall
  };
};
